"""product images

Ревизия: 8b43f6e87841
Предыдущая: 90e074e29ae1
Создана: 2026-09-04 20:27:51.688422

Дополнительные фотографии товара (ТЗ 2.2.4, 13; ROADMAP 2.11). Обложка
остаётся в `products.image_key` — не трогаем и не переносим: эта
таблица только про ОСТАЛЬНЫЕ фото, показанные на карточке галереей.
Ссылка на файл — тот же справочник Wikimedia (`domain/photos.py`), не
приём произвольных файлов.

Откат безопасен: `downgrade()` сносит только новую таблицу, данные
других таблиц не затрагивает.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b43f6e87841'
down_revision: Union[str, None] = '90e074e29ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
