"""baseline

Ревизия: 90e074e29ae1
Предыдущая:
Создана: 2026-09-03 23:12:44.717233

Первая ревизия — фиксирует схему, которую до сих пор собирал
`models.py --create` (см. `backend/alembic/versions/README.md`). Она не
меняет ничего нового: 20 таблиц один в один повторяют `db/models.py` на
момент перехода на alembic (ROADMAP.md 3.1).

На боевой базе, где эта схема уже есть, вместо `upgrade` нужно
`alembic stamp head` — иначе `upgrade` попробует создать таблицы
заново и упадёт на дубликате. На пустой базе (новый сервер, тестовый
стенд) — обычный `alembic upgrade head`.

Дальше схему меняет только новая ревизия, `models.py --create` остаётся
только для самого первого разворачивания роли и базы.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90e074e29ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_action'), 'audit', ['action'], unique=False)
    op.create_index(op.f('ix_audit_actor'), 'audit', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_at'), 'audit', ['at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('free_from', sa.Integer(), nullable=True),
    sa.Column('manual_quote', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meat_bookings',
    sa.Column('ymd', sa.String(length=10), nullable=False),
    sa.Column('booked_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ymd')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_phone'), 'otp', ['phone'], unique=False)
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_order', sa.Integer(), nullable=False),
    sa.Column('uses_limit', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocodes_code'), 'promocodes', ['code'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('slot_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('ymd', sa.String(length=10), nullable=False),
    sa.Column('slot_from', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'ymd', 'slot_from', name='uq_slot')
    )
    op.create_index(op.f('ix_slot_bookings_ymd'), 'slot_bookings', ['ymd'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('slot_ymd', sa.String(length=10), nullable=True),
    sa.Column('slot_from', sa.Integer(), nullable=True),
    sa.Column('slot_to', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=True),
    sa.Column('promocode', sa.String(length=64), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('delivery_discount', sa.Integer(), nullable=False),
    sa.Column('delivery_cost', sa.Integer(), nullable=False),
    sa.Column('agreed_delivery_cost', sa.Integer(), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('hold_amount', sa.Integer(), nullable=False),
    sa.Column('planned_total', sa.Integer(), nullable=False),
    sa.Column('telegram_optin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_phone'), 'orders', ['phone'], unique=False)
    op.create_index(op.f('ix_orders_slot_ymd'), 'orders', ['slot_ymd'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('sale_until', sa.String(length=10), nullable=True),
    sa.Column('vat_rate', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=False),
    sa.Column('weight_step', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('image_key', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('promo_code', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('last_seen', sa.String(length=40), nullable=True),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_sid'), 'sessions', ['sid'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tg_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_links_token'), 'tg_links', ['token'], unique=True)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'product_id', name='uq_cart_session_product')
    )
    op.create_index(op.f('ix_cart_items_session_id'), 'cart_items', ['session_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=True),
    sa.Column('requested_weight', sa.Float(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('weight_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('price_at_purchase', sa.Integer(), nullable=False),
    sa.Column('was_sale', sa.Boolean(), nullable=False),
    sa.Column('vat_rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('preorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('requested_weight', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.Column('estimate', sa.Integer(), nullable=False),
    sa.Column('pickup_date', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preorders_number'), 'preorders', ['number'], unique=True)
    op.create_index(op.f('ix_preorders_phone'), 'preorders', ['phone'], unique=False)
    op.create_index(op.f('ix_preorders_pickup_date'), 'preorders', ['pickup_date'], unique=False)
    op.create_index(op.f('ix_preorders_status'), 'preorders', ['status'], unique=False)
    op.create_table('promocode_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocode_usages_phone'), 'promocode_usages', ['phone'], unique=False)
    op.create_index(op.f('ix_promocode_usages_promocode_id'), 'promocode_usages', ['promocode_id'], unique=False)
    op.create_table('session_recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'kind', 'ref_id', name='uq_session_recent')
    )
    op.create_index(op.f('ix_session_recent_session_id'), 'session_recent', ['session_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('preorder_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('personal_data', sa.Boolean(), nullable=False),
    sa.Column('marketing', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preorder_id'], ['preorders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    op.drop_index(op.f('ix_session_recent_session_id'), table_name='session_recent')
    op.drop_table('session_recent')
    op.drop_index(op.f('ix_promocode_usages_promocode_id'), table_name='promocode_usages')
    op.drop_index(op.f('ix_promocode_usages_phone'), table_name='promocode_usages')
    op.drop_table('promocode_usages')
    op.drop_index(op.f('ix_preorders_status'), table_name='preorders')
    op.drop_index(op.f('ix_preorders_pickup_date'), table_name='preorders')
    op.drop_index(op.f('ix_preorders_phone'), table_name='preorders')
    op.drop_index(op.f('ix_preorders_number'), table_name='preorders')
    op.drop_table('preorders')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_items_session_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_tg_links_token'), table_name='tg_links')
    op.drop_table('tg_links')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_sid'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_slot_ymd'), table_name='orders')
    op.drop_index(op.f('ix_orders_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slot_bookings_ymd'), table_name='slot_bookings')
    op.drop_table('slot_bookings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_promocodes_code'), table_name='promocodes')
    op.drop_table('promocodes')
    op.drop_index(op.f('ix_otp_phone'), table_name='otp')
    op.drop_table('otp')
    op.drop_table('meat_bookings')
    op.drop_table('delivery_zones')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_at'), table_name='audit')
    op.drop_index(op.f('ix_audit_actor'), table_name='audit')
    op.drop_index(op.f('ix_audit_action'), table_name='audit')
    op.drop_table('audit')
    # ### end Alembic commands ###
